export const ROUTES = {
  HOME: "/",
  PROFILE: "/profile",
  MARKETPLACE: "/marketplace",
  MARKETPLACE_CATEGORY: "/marketplace/:category",
  POSTS: "/posts",
  UPGRADE: "/upgrade",
  CART: "/cart",
  CHECKOUT: "/checkout",
  SUCCESS: "/checkout/success",
  FAIL: "/checkout/fail",
  DEPOSIT: "/checkout/deposit",
  ADMIN: {
    DASHBOARD: "/admin",
    USERS: "/admin/users",
    LISTINGS: "/admin/listings",
    FEES: "/admin/fees",
    TRANSACTIONS: "/admin/transactions",
  },
  NOT_FOUND: "*",
};
